export const project = {
	description: 'projects.yem.description',
	highlights: [
		'projects.yem.highlights.awsCognito',
		'projects.yem.highlights.hotmart',
		'projects.yem.highlights.mautic',
		'projects.yem.highlights.postgres',
		'projects.yem.highlights.prismaOrm',
	],
	link: 'https://yogaemmovimento.com',
	technologies: [
		'React',
		'Ract Router',
		'Docker',
		'Docker compose',
		'Mautic',
		'Postgres',
		'Prisma ORM',
		'Typescript',
		'Github Actions',
		'Tailwind',
		'Biome',
		'Vite',
		'AWS Cognito',
		'AWS SES',
		'Radix Colors',
		'Radix Primitives',
		'Joi',
		'Motion',
		'Hotmart',
		'WhatsApp API',
		'Google Tag Manager',
		'Google Analytics',
		'Google Search Console',
	],
	title: 'projects.yem.title',
};
